/********************************************************************************
** Form generated from reading UI file 'codestreamtranslator.ui'
**
** Created by: Qt User Interface Compiler version 6.2.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CODESTREAMTRANSLATOR_H
#define UI_CODESTREAMTRANSLATOR_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CodeStreamTranslator
{
public:
    QLabel *mess_label;
    QTextEdit *messbox_TextEdit;
    QPushButton *translateButton;
    QLabel *messType_label;
    QLabel *messTypeContent_label;
    QLabel *byte2_Label;
    QLabel *byte3_Label;
    QLabel *byte6_Label;
    QLabel *byte8_Label;
    QLabel *byte1_Label;
    QLabel *byte7_Label;
    QLabel *byte5_Label;
    QLabel *byte4_Label;
    QLabel *byte19_Label;
    QLabel *byteContent_19_Label;
    QLabel *byteContent_26_Label;
    QLabel *byte26_Label;
    QLabel *byteContent_14_Label;
    QLabel *byte14_Label;
    QLabel *byte20_Label;
    QLabel *byteContent_20_Label;
    QLabel *byte22_Label;
    QLabel *byteContent_22_Label;
    QLabel *byte12_Label;
    QLabel *byteContent_12_Label;
    QLabel *byteContent_15_Label;
    QLabel *byte15_Label;
    QLabel *byte29_Label;
    QLabel *byteContent_29_Label;
    QLabel *byte13_Label;
    QLabel *byteContent_13_Label;
    QLabel *byte32_Label;
    QLabel *byteContent_32_Label;
    QLabel *byte30_Label;
    QLabel *byteContent_30_Label;
    QLabel *byte11_Label;
    QLabel *byteContent_11_Label;
    QLabel *byteContent_24_Label;
    QLabel *byte24_Label;
    QLabel *byteContent_16_Label;
    QLabel *byte16_Label;
    QLabel *byte31_Label;
    QLabel *byteContent_31_Label;
    QLabel *byte9_Label;
    QLabel *byteContent_9_Label;
    QLabel *byte17_Label;
    QLabel *byteContent_17_Label;
    QLabel *byte25_Label;
    QLabel *byteContent_25_Label;
    QLabel *byte21_Label;
    QLabel *byteContent_21_Label;
    QLabel *byteContent_23_Label;
    QLabel *byte23_Label;
    QLabel *byte10_Label;
    QLabel *byteContent_10_Label;
    QLabel *byte18_Label;
    QLabel *byteContent_18_Label;
    QLabel *byte28_Label;
    QLabel *byteContent_28_Label;
    QLabel *byte27_Label;
    QLabel *byteContent_27_Label;
    QLabel *byteContent_5_Label;
    QLabel *byteContent_6_Label;
    QLabel *byteContent_3_Label;
    QLabel *byteContent_4_Label;
    QLabel *byteContent_8_Label;
    QLabel *byteContent_7_Label;
    QLabel *byteContent_1_Label;
    QLabel *byteContent_2_Label;

    void setupUi(QWidget *CodeStreamTranslator)
    {
        if (CodeStreamTranslator->objectName().isEmpty())
            CodeStreamTranslator->setObjectName(QString::fromUtf8("CodeStreamTranslator"));
        CodeStreamTranslator->resize(992, 501);
        mess_label = new QLabel(CodeStreamTranslator);
        mess_label->setObjectName(QString::fromUtf8("mess_label"));
        mess_label->setGeometry(QRect(50, 40, 70, 90));
        QFont font;
        font.setPointSize(12);
        mess_label->setFont(font);
        mess_label->setAlignment(Qt::AlignCenter);
        messbox_TextEdit = new QTextEdit(CodeStreamTranslator);
        messbox_TextEdit->setObjectName(QString::fromUtf8("messbox_TextEdit"));
        messbox_TextEdit->setGeometry(QRect(140, 40, 620, 90));
        translateButton = new QPushButton(CodeStreamTranslator);
        translateButton->setObjectName(QString::fromUtf8("translateButton"));
        translateButton->setGeometry(QRect(790, 40, 130, 90));
        translateButton->setFont(font);
        messType_label = new QLabel(CodeStreamTranslator);
        messType_label->setObjectName(QString::fromUtf8("messType_label"));
        messType_label->setGeometry(QRect(50, 150, 70, 30));
        QFont font1;
        font1.setPointSize(10);
        messType_label->setFont(font1);
        messType_label->setAlignment(Qt::AlignCenter);
        messTypeContent_label = new QLabel(CodeStreamTranslator);
        messTypeContent_label->setObjectName(QString::fromUtf8("messTypeContent_label"));
        messTypeContent_label->setGeometry(QRect(140, 150, 840, 30));
        messTypeContent_label->setFont(font1);
        byte2_Label = new QLabel(CodeStreamTranslator);
        byte2_Label->setObjectName(QString::fromUtf8("byte2_Label"));
        byte2_Label->setGeometry(QRect(50, 230, 15, 16));
        byte2_Label->setAlignment(Qt::AlignCenter);
        byte3_Label = new QLabel(CodeStreamTranslator);
        byte3_Label->setObjectName(QString::fromUtf8("byte3_Label"));
        byte3_Label->setGeometry(QRect(50, 260, 15, 16));
        byte3_Label->setAlignment(Qt::AlignCenter);
        byte6_Label = new QLabel(CodeStreamTranslator);
        byte6_Label->setObjectName(QString::fromUtf8("byte6_Label"));
        byte6_Label->setGeometry(QRect(50, 350, 15, 16));
        byte6_Label->setAlignment(Qt::AlignCenter);
        byte8_Label = new QLabel(CodeStreamTranslator);
        byte8_Label->setObjectName(QString::fromUtf8("byte8_Label"));
        byte8_Label->setGeometry(QRect(50, 410, 15, 16));
        byte8_Label->setAlignment(Qt::AlignCenter);
        byte1_Label = new QLabel(CodeStreamTranslator);
        byte1_Label->setObjectName(QString::fromUtf8("byte1_Label"));
        byte1_Label->setGeometry(QRect(50, 200, 15, 16));
        byte1_Label->setAlignment(Qt::AlignCenter);
        byte7_Label = new QLabel(CodeStreamTranslator);
        byte7_Label->setObjectName(QString::fromUtf8("byte7_Label"));
        byte7_Label->setGeometry(QRect(50, 380, 15, 16));
        byte7_Label->setAlignment(Qt::AlignCenter);
        byte5_Label = new QLabel(CodeStreamTranslator);
        byte5_Label->setObjectName(QString::fromUtf8("byte5_Label"));
        byte5_Label->setGeometry(QRect(50, 320, 15, 16));
        byte5_Label->setAlignment(Qt::AlignCenter);
        byte4_Label = new QLabel(CodeStreamTranslator);
        byte4_Label->setObjectName(QString::fromUtf8("byte4_Label"));
        byte4_Label->setGeometry(QRect(50, 290, 15, 16));
        byte4_Label->setAlignment(Qt::AlignCenter);
        byte19_Label = new QLabel(CodeStreamTranslator);
        byte19_Label->setObjectName(QString::fromUtf8("byte19_Label"));
        byte19_Label->setGeometry(QRect(530, 260, 15, 16));
        byte19_Label->setAlignment(Qt::AlignCenter);
        byteContent_19_Label = new QLabel(CodeStreamTranslator);
        byteContent_19_Label->setObjectName(QString::fromUtf8("byteContent_19_Label"));
        byteContent_19_Label->setGeometry(QRect(550, 260, 190, 16));
        byteContent_26_Label = new QLabel(CodeStreamTranslator);
        byteContent_26_Label->setObjectName(QString::fromUtf8("byteContent_26_Label"));
        byteContent_26_Label->setGeometry(QRect(790, 230, 190, 16));
        byte26_Label = new QLabel(CodeStreamTranslator);
        byte26_Label->setObjectName(QString::fromUtf8("byte26_Label"));
        byte26_Label->setGeometry(QRect(770, 230, 15, 16));
        byte26_Label->setAlignment(Qt::AlignCenter);
        byteContent_14_Label = new QLabel(CodeStreamTranslator);
        byteContent_14_Label->setObjectName(QString::fromUtf8("byteContent_14_Label"));
        byteContent_14_Label->setGeometry(QRect(310, 350, 190, 16));
        byte14_Label = new QLabel(CodeStreamTranslator);
        byte14_Label->setObjectName(QString::fromUtf8("byte14_Label"));
        byte14_Label->setGeometry(QRect(290, 350, 15, 16));
        byte14_Label->setAlignment(Qt::AlignCenter);
        byte20_Label = new QLabel(CodeStreamTranslator);
        byte20_Label->setObjectName(QString::fromUtf8("byte20_Label"));
        byte20_Label->setGeometry(QRect(530, 290, 15, 16));
        byte20_Label->setAlignment(Qt::AlignCenter);
        byteContent_20_Label = new QLabel(CodeStreamTranslator);
        byteContent_20_Label->setObjectName(QString::fromUtf8("byteContent_20_Label"));
        byteContent_20_Label->setGeometry(QRect(550, 290, 190, 16));
        byte22_Label = new QLabel(CodeStreamTranslator);
        byte22_Label->setObjectName(QString::fromUtf8("byte22_Label"));
        byte22_Label->setGeometry(QRect(530, 350, 15, 16));
        byte22_Label->setAlignment(Qt::AlignCenter);
        byteContent_22_Label = new QLabel(CodeStreamTranslator);
        byteContent_22_Label->setObjectName(QString::fromUtf8("byteContent_22_Label"));
        byteContent_22_Label->setGeometry(QRect(550, 350, 190, 16));
        byte12_Label = new QLabel(CodeStreamTranslator);
        byte12_Label->setObjectName(QString::fromUtf8("byte12_Label"));
        byte12_Label->setGeometry(QRect(290, 290, 15, 16));
        byte12_Label->setAlignment(Qt::AlignCenter);
        byteContent_12_Label = new QLabel(CodeStreamTranslator);
        byteContent_12_Label->setObjectName(QString::fromUtf8("byteContent_12_Label"));
        byteContent_12_Label->setGeometry(QRect(310, 290, 190, 16));
        byteContent_15_Label = new QLabel(CodeStreamTranslator);
        byteContent_15_Label->setObjectName(QString::fromUtf8("byteContent_15_Label"));
        byteContent_15_Label->setGeometry(QRect(310, 380, 190, 16));
        byte15_Label = new QLabel(CodeStreamTranslator);
        byte15_Label->setObjectName(QString::fromUtf8("byte15_Label"));
        byte15_Label->setGeometry(QRect(290, 380, 15, 16));
        byte15_Label->setAlignment(Qt::AlignCenter);
        byte29_Label = new QLabel(CodeStreamTranslator);
        byte29_Label->setObjectName(QString::fromUtf8("byte29_Label"));
        byte29_Label->setGeometry(QRect(770, 320, 15, 16));
        byte29_Label->setAlignment(Qt::AlignCenter);
        byteContent_29_Label = new QLabel(CodeStreamTranslator);
        byteContent_29_Label->setObjectName(QString::fromUtf8("byteContent_29_Label"));
        byteContent_29_Label->setGeometry(QRect(790, 320, 190, 16));
        byte13_Label = new QLabel(CodeStreamTranslator);
        byte13_Label->setObjectName(QString::fromUtf8("byte13_Label"));
        byte13_Label->setGeometry(QRect(290, 320, 15, 16));
        byte13_Label->setAlignment(Qt::AlignCenter);
        byteContent_13_Label = new QLabel(CodeStreamTranslator);
        byteContent_13_Label->setObjectName(QString::fromUtf8("byteContent_13_Label"));
        byteContent_13_Label->setGeometry(QRect(310, 320, 190, 16));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Ignored);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(byteContent_13_Label->sizePolicy().hasHeightForWidth());
        byteContent_13_Label->setSizePolicy(sizePolicy);
        byteContent_13_Label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        byte32_Label = new QLabel(CodeStreamTranslator);
        byte32_Label->setObjectName(QString::fromUtf8("byte32_Label"));
        byte32_Label->setGeometry(QRect(770, 410, 15, 16));
        byte32_Label->setAlignment(Qt::AlignCenter);
        byteContent_32_Label = new QLabel(CodeStreamTranslator);
        byteContent_32_Label->setObjectName(QString::fromUtf8("byteContent_32_Label"));
        byteContent_32_Label->setGeometry(QRect(790, 410, 190, 16));
        byte30_Label = new QLabel(CodeStreamTranslator);
        byte30_Label->setObjectName(QString::fromUtf8("byte30_Label"));
        byte30_Label->setGeometry(QRect(770, 350, 15, 16));
        byte30_Label->setAlignment(Qt::AlignCenter);
        byteContent_30_Label = new QLabel(CodeStreamTranslator);
        byteContent_30_Label->setObjectName(QString::fromUtf8("byteContent_30_Label"));
        byteContent_30_Label->setGeometry(QRect(790, 350, 190, 16));
        byte11_Label = new QLabel(CodeStreamTranslator);
        byte11_Label->setObjectName(QString::fromUtf8("byte11_Label"));
        byte11_Label->setGeometry(QRect(290, 260, 15, 16));
        byte11_Label->setAlignment(Qt::AlignCenter);
        byteContent_11_Label = new QLabel(CodeStreamTranslator);
        byteContent_11_Label->setObjectName(QString::fromUtf8("byteContent_11_Label"));
        byteContent_11_Label->setGeometry(QRect(310, 260, 190, 16));
        byteContent_24_Label = new QLabel(CodeStreamTranslator);
        byteContent_24_Label->setObjectName(QString::fromUtf8("byteContent_24_Label"));
        byteContent_24_Label->setGeometry(QRect(550, 410, 190, 16));
        byte24_Label = new QLabel(CodeStreamTranslator);
        byte24_Label->setObjectName(QString::fromUtf8("byte24_Label"));
        byte24_Label->setGeometry(QRect(530, 410, 15, 16));
        byte24_Label->setAlignment(Qt::AlignCenter);
        byteContent_16_Label = new QLabel(CodeStreamTranslator);
        byteContent_16_Label->setObjectName(QString::fromUtf8("byteContent_16_Label"));
        byteContent_16_Label->setGeometry(QRect(310, 410, 190, 16));
        byte16_Label = new QLabel(CodeStreamTranslator);
        byte16_Label->setObjectName(QString::fromUtf8("byte16_Label"));
        byte16_Label->setGeometry(QRect(290, 410, 15, 16));
        byte16_Label->setAlignment(Qt::AlignCenter);
        byte31_Label = new QLabel(CodeStreamTranslator);
        byte31_Label->setObjectName(QString::fromUtf8("byte31_Label"));
        byte31_Label->setGeometry(QRect(770, 380, 15, 16));
        byte31_Label->setAlignment(Qt::AlignCenter);
        byteContent_31_Label = new QLabel(CodeStreamTranslator);
        byteContent_31_Label->setObjectName(QString::fromUtf8("byteContent_31_Label"));
        byteContent_31_Label->setGeometry(QRect(790, 380, 190, 16));
        byte9_Label = new QLabel(CodeStreamTranslator);
        byte9_Label->setObjectName(QString::fromUtf8("byte9_Label"));
        byte9_Label->setGeometry(QRect(290, 200, 15, 16));
        byte9_Label->setAlignment(Qt::AlignCenter);
        byteContent_9_Label = new QLabel(CodeStreamTranslator);
        byteContent_9_Label->setObjectName(QString::fromUtf8("byteContent_9_Label"));
        byteContent_9_Label->setGeometry(QRect(310, 200, 190, 16));
        byte17_Label = new QLabel(CodeStreamTranslator);
        byte17_Label->setObjectName(QString::fromUtf8("byte17_Label"));
        byte17_Label->setGeometry(QRect(530, 200, 15, 16));
        byte17_Label->setAlignment(Qt::AlignCenter);
        byteContent_17_Label = new QLabel(CodeStreamTranslator);
        byteContent_17_Label->setObjectName(QString::fromUtf8("byteContent_17_Label"));
        byteContent_17_Label->setGeometry(QRect(550, 200, 190, 16));
        byte25_Label = new QLabel(CodeStreamTranslator);
        byte25_Label->setObjectName(QString::fromUtf8("byte25_Label"));
        byte25_Label->setGeometry(QRect(770, 200, 15, 16));
        byte25_Label->setAlignment(Qt::AlignCenter);
        byteContent_25_Label = new QLabel(CodeStreamTranslator);
        byteContent_25_Label->setObjectName(QString::fromUtf8("byteContent_25_Label"));
        byteContent_25_Label->setGeometry(QRect(790, 200, 190, 16));
        byte21_Label = new QLabel(CodeStreamTranslator);
        byte21_Label->setObjectName(QString::fromUtf8("byte21_Label"));
        byte21_Label->setGeometry(QRect(530, 320, 15, 16));
        byte21_Label->setAlignment(Qt::AlignCenter);
        byteContent_21_Label = new QLabel(CodeStreamTranslator);
        byteContent_21_Label->setObjectName(QString::fromUtf8("byteContent_21_Label"));
        byteContent_21_Label->setGeometry(QRect(550, 320, 190, 16));
        byteContent_23_Label = new QLabel(CodeStreamTranslator);
        byteContent_23_Label->setObjectName(QString::fromUtf8("byteContent_23_Label"));
        byteContent_23_Label->setGeometry(QRect(550, 380, 190, 16));
        byte23_Label = new QLabel(CodeStreamTranslator);
        byte23_Label->setObjectName(QString::fromUtf8("byte23_Label"));
        byte23_Label->setGeometry(QRect(530, 380, 15, 16));
        byte23_Label->setAlignment(Qt::AlignCenter);
        byte10_Label = new QLabel(CodeStreamTranslator);
        byte10_Label->setObjectName(QString::fromUtf8("byte10_Label"));
        byte10_Label->setGeometry(QRect(290, 230, 15, 16));
        byte10_Label->setAlignment(Qt::AlignCenter);
        byteContent_10_Label = new QLabel(CodeStreamTranslator);
        byteContent_10_Label->setObjectName(QString::fromUtf8("byteContent_10_Label"));
        byteContent_10_Label->setGeometry(QRect(310, 230, 190, 16));
        byte18_Label = new QLabel(CodeStreamTranslator);
        byte18_Label->setObjectName(QString::fromUtf8("byte18_Label"));
        byte18_Label->setGeometry(QRect(530, 230, 15, 16));
        byte18_Label->setAlignment(Qt::AlignCenter);
        byteContent_18_Label = new QLabel(CodeStreamTranslator);
        byteContent_18_Label->setObjectName(QString::fromUtf8("byteContent_18_Label"));
        byteContent_18_Label->setGeometry(QRect(550, 230, 190, 16));
        byte28_Label = new QLabel(CodeStreamTranslator);
        byte28_Label->setObjectName(QString::fromUtf8("byte28_Label"));
        byte28_Label->setGeometry(QRect(770, 290, 15, 16));
        byte28_Label->setAlignment(Qt::AlignCenter);
        byteContent_28_Label = new QLabel(CodeStreamTranslator);
        byteContent_28_Label->setObjectName(QString::fromUtf8("byteContent_28_Label"));
        byteContent_28_Label->setGeometry(QRect(790, 290, 190, 16));
        byte27_Label = new QLabel(CodeStreamTranslator);
        byte27_Label->setObjectName(QString::fromUtf8("byte27_Label"));
        byte27_Label->setGeometry(QRect(770, 260, 15, 16));
        byte27_Label->setAlignment(Qt::AlignCenter);
        byteContent_27_Label = new QLabel(CodeStreamTranslator);
        byteContent_27_Label->setObjectName(QString::fromUtf8("byteContent_27_Label"));
        byteContent_27_Label->setGeometry(QRect(790, 260, 190, 16));
        byteContent_5_Label = new QLabel(CodeStreamTranslator);
        byteContent_5_Label->setObjectName(QString::fromUtf8("byteContent_5_Label"));
        byteContent_5_Label->setGeometry(QRect(70, 320, 190, 16));
        byteContent_6_Label = new QLabel(CodeStreamTranslator);
        byteContent_6_Label->setObjectName(QString::fromUtf8("byteContent_6_Label"));
        byteContent_6_Label->setGeometry(QRect(70, 350, 190, 16));
        byteContent_3_Label = new QLabel(CodeStreamTranslator);
        byteContent_3_Label->setObjectName(QString::fromUtf8("byteContent_3_Label"));
        byteContent_3_Label->setGeometry(QRect(70, 260, 190, 16));
        byteContent_4_Label = new QLabel(CodeStreamTranslator);
        byteContent_4_Label->setObjectName(QString::fromUtf8("byteContent_4_Label"));
        byteContent_4_Label->setGeometry(QRect(70, 290, 190, 16));
        byteContent_8_Label = new QLabel(CodeStreamTranslator);
        byteContent_8_Label->setObjectName(QString::fromUtf8("byteContent_8_Label"));
        byteContent_8_Label->setGeometry(QRect(70, 410, 190, 16));
        byteContent_7_Label = new QLabel(CodeStreamTranslator);
        byteContent_7_Label->setObjectName(QString::fromUtf8("byteContent_7_Label"));
        byteContent_7_Label->setGeometry(QRect(70, 380, 190, 16));
        byteContent_1_Label = new QLabel(CodeStreamTranslator);
        byteContent_1_Label->setObjectName(QString::fromUtf8("byteContent_1_Label"));
        byteContent_1_Label->setGeometry(QRect(70, 200, 190, 16));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(byteContent_1_Label->sizePolicy().hasHeightForWidth());
        byteContent_1_Label->setSizePolicy(sizePolicy1);
        byteContent_1_Label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        byteContent_2_Label = new QLabel(CodeStreamTranslator);
        byteContent_2_Label->setObjectName(QString::fromUtf8("byteContent_2_Label"));
        byteContent_2_Label->setGeometry(QRect(70, 230, 190, 16));

        retranslateUi(CodeStreamTranslator);

        QMetaObject::connectSlotsByName(CodeStreamTranslator);
    } // setupUi

    void retranslateUi(QWidget *CodeStreamTranslator)
    {
        CodeStreamTranslator->setWindowTitle(QCoreApplication::translate("CodeStreamTranslator", "CodeStreamTranslator", nullptr));
        mess_label->setText(QCoreApplication::translate("CodeStreamTranslator", "\346\266\210\346\201\257", nullptr));
        translateButton->setText(QCoreApplication::translate("CodeStreamTranslator", "\347\277\273\350\257\221", nullptr));
        messType_label->setText(QCoreApplication::translate("CodeStreamTranslator", "\346\266\210\346\201\257\347\261\273\345\236\213", nullptr));
        messTypeContent_label->setText(QCoreApplication::translate("CodeStreamTranslator", "messType", nullptr));
        byte2_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "2", nullptr));
        byte3_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "3", nullptr));
        byte6_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "6", nullptr));
        byte8_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "8", nullptr));
        byte1_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "1", nullptr));
        byte7_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "7", nullptr));
        byte5_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "5", nullptr));
        byte4_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "4", nullptr));
        byte19_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "19", nullptr));
        byteContent_19_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 19", nullptr));
        byteContent_26_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 26", nullptr));
        byte26_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "26", nullptr));
        byteContent_14_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 14", nullptr));
        byte14_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "14", nullptr));
        byte20_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "20", nullptr));
        byteContent_20_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 20", nullptr));
        byte22_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "22", nullptr));
        byteContent_22_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 22", nullptr));
        byte12_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "12", nullptr));
        byteContent_12_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 12", nullptr));
        byteContent_15_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 15", nullptr));
        byte15_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "15", nullptr));
        byte29_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "29", nullptr));
        byteContent_29_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 29", nullptr));
        byte13_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "13", nullptr));
        byteContent_13_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 13", nullptr));
        byte32_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "32", nullptr));
        byteContent_32_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 32", nullptr));
        byte30_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "30", nullptr));
        byteContent_30_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 30", nullptr));
        byte11_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "11", nullptr));
        byteContent_11_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 11", nullptr));
        byteContent_24_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 24", nullptr));
        byte24_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "24", nullptr));
        byteContent_16_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 16", nullptr));
        byte16_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "16", nullptr));
        byte31_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "31", nullptr));
        byteContent_31_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 31", nullptr));
        byte9_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "9", nullptr));
        byteContent_9_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 9", nullptr));
        byte17_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "17", nullptr));
        byteContent_17_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 17", nullptr));
        byte25_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "25", nullptr));
        byteContent_25_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 25", nullptr));
        byte21_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "21", nullptr));
        byteContent_21_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 21", nullptr));
        byteContent_23_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 23", nullptr));
        byte23_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "23", nullptr));
        byte10_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "10", nullptr));
        byteContent_10_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 10", nullptr));
        byte18_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "18", nullptr));
        byteContent_18_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 18", nullptr));
        byte28_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "28", nullptr));
        byteContent_28_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 28", nullptr));
        byte27_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "27", nullptr));
        byteContent_27_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 27", nullptr));
        byteContent_5_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 5", nullptr));
        byteContent_6_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 6", nullptr));
        byteContent_3_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 3", nullptr));
        byteContent_4_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 4", nullptr));
        byteContent_8_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 8", nullptr));
        byteContent_7_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 7", nullptr));
        byteContent_1_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 1", nullptr));
        byteContent_2_Label->setText(QCoreApplication::translate("CodeStreamTranslator", "byteContent 2", nullptr));
    } // retranslateUi

};

namespace Ui {
    class CodeStreamTranslator: public Ui_CodeStreamTranslator {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CODESTREAMTRANSLATOR_H
